# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LTJ4qLaSOsfldWOEr+bJCv7twctnJ9jmA4pe3ewh4hU1AhG+pKZnTspK7BVK7B4QxAetIwy2j3rPLTqpZ0tGQWOfsmIeuHrkiJPLcMHau5Fex9L1AjIERvx0nMrnmn1FWos9wmUUsF1gAAHPXyQijcuEVL/8pA69Z23CYO9/K8RciF1LFLzHBSVYgUyJiamCcANKA8HB+nYPXtP98aoQU5Bk+ITUatgnqKv/NqbMOlNfJTN0cD5foksKlTqCSqpq9GJT18F7zmxi7/hB4+1dV75xhZYZZh95QbzMyA+j1CLuRfbttT1WXPUFDnT8y80DzMe1UAlsogZOdEUX+fXUelBzb16XrbwQx4mnSieJ0czuLz+POOuRvQTDd0XXnXnkGqh7NIV3oGiU4gz7K9HNdZANXomKp2k9SYDL1lSDdG5gHJlizUjqOGC7n90oYVOPMf/7IAMeeiXVgKiuYs4AW/MC9uSgVTKOj1tvQgGrTPJLDSQHwrVCqkEkm1txuM8w8diWLmwS0r/XlkXPVJvSRYNVIpfjRf45J+6zSDrmRBwDksRiZto/j9TxGoQW2cCRIfSXXgHxxhndizguqvHm1zzUAF5fawjtNJQFiEakAnGkFtx/1H1jIID/Zo0Eymwlj/HY8idwR/uBbSHrnTnOdA9RAHgN0OLlneRCGRr536c="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
