travis:
  secure:
    BINSTAR_TOKEN: LTJ4qLaSOsfldWOEr+bJCv7twctnJ9jmA4pe3ewh4hU1AhG+pKZnTspK7BVK7B4QxAetIwy2j3rPLTqpZ0tGQWOfsmIeuHrkiJPLcMHau5Fex9L1AjIERvx0nMrnmn1FWos9wmUUsF1gAAHPXyQijcuEVL/8pA69Z23CYO9/K8RciF1LFLzHBSVYgUyJiamCcANKA8HB+nYPXtP98aoQU5Bk+ITUatgnqKv/NqbMOlNfJTN0cD5foksKlTqCSqpq9GJT18F7zmxi7/hB4+1dV75xhZYZZh95QbzMyA+j1CLuRfbttT1WXPUFDnT8y80DzMe1UAlsogZOdEUX+fXUelBzb16XrbwQx4mnSieJ0czuLz+POOuRvQTDd0XXnXnkGqh7NIV3oGiU4gz7K9HNdZANXomKp2k9SYDL1lSDdG5gHJlizUjqOGC7n90oYVOPMf/7IAMeeiXVgKiuYs4AW/MC9uSgVTKOj1tvQgGrTPJLDSQHwrVCqkEkm1txuM8w8diWLmwS0r/XlkXPVJvSRYNVIpfjRf45J+6zSDrmRBwDksRiZto/j9TxGoQW2cCRIfSXXgHxxhndizguqvHm1zzUAF5fawjtNJQFiEakAnGkFtx/1H1jIID/Zo0Eymwlj/HY8idwR/uBbSHrnTnOdA9RAHgN0OLlneRCGRr536c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
